spring:
  application:
    name: order_managerment_service
  datasource:
    url: jdbc:h2:mem:OrdersDB       
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true

server:
  port: 8001