spring:
  application:
    name: order_managerment_service
  
  datasource:
    url: jdbc:mysql://localhost:3006/orders_db
    # url: jdbc:h2:mem:OrdersDB       
    username: nonroot
    password: notsafe##db
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driverClassName: org.h2.Driver
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true

server:
  port: 8001